# Generated by Django 5.0.14 on 2026-05-03 11:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('transfer', 'Transfer'), ('withdrawal', 'Withdrawal')], max_length=20)),
                ('reference_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
